apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: freshtuna-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - "*.freshtuna.me"
    secretName: "freshtuna-me"
  rules:
  - host: "knufesta2019.freshtuna.me"
    http:
      paths:
      - path: /
        backend:
          serviceName: "production-was.knufesta2019.svc"
          servicePort: 80
