apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: freshtuna-ingress
  namespace: default
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - "*.freshtuna.me"
    secretName: "freshtuna-me"
  rules:
  - host: "knufesta2019.freshtuna.me"
    http:
      paths:
      - path: /
        backend:
          serviceName: "production-was.knufesta2019.svc"
          servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: freshtuna-ingress
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30000
    - name: https
      port: 443
      targetPort: https
      nodePort: 30000
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
